# Generated by Django 3.2.7 on 2022-07-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groundapp', '0002_alter_owner_timings'),
        ('ownerapp', '0005_auto_20220609_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.TextField()),
                ('description', models.TextField(default=0)),
                ('cost', models.BigIntegerField()),
                ('hours', models.BigIntegerField(default=1)),
                ('final_cost', models.BigIntegerField()),
                ('status', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundapp.customer')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerapp.add_ground')),
            ],
        ),
    ]
