# Generated by Django 3.2.7 on 2022-05-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_ground',
            name='password',
        ),
    ]
