# Generated by Django 3.2.7 on 2022-05-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0002_remove_add_ground_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_ground',
            name='address',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
