# Generated by Django 3.2.7 on 2022-06-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0003_add_ground_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_ground',
            name='evening_slot_cost',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_ground',
            name='morning_slot_cost',
            field=models.BigIntegerField(default=50),
            preserve_default=False,
        ),
    ]
