# Generated by Django 3.2.7 on 2022-06-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0004_auto_20220609_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_ground',
            old_name='evening_slot_cost',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='add_ground',
            name='morning_slot_cost',
        ),
    ]
